name: Docker Image Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/swyp6 \
          --build-arg DB_NAME=${{ secrets.DB_NAME }} \
          --build-arg MYSQL_USERNAME=${{ secrets.MYSQL_USERNAME }} \
          --build-arg MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
          --build-arg DB_IP=${{ secrets.DB_IP }} \
          --build-arg UPLOAD_ROOT=${{ secrets.UPLOAD_ROOT }} \
          --build-arg KAKAO_REDIRECT_URI=${{ secrets.KAKAO_REDIRECT_URI }} \
          --build-arg KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }} \
          --build-arg KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }} \
          --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
          --build-arg ALLOW_ORIGIN=${{ secrets.ALLOW_ORIGIN }}

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: docker Hub push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/swyp6
