name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Build the Docker image
        run: docker build . --file Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/swyp6


      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: docker Hub push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/swyp6



      - name: Deploy to dev
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DEV }} # EC2 퍼블릭 IPv4 DNS
          username: ${{ secrets.USERNAME }} # ubuntu
          password: ${{ secrets.PASSWORD }}
          port: 22
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            sudo docker ps
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME  }}/swyp6
            sudo docker stop swyp6-back
            sudo docker rm swyp6-back
            sudo docker run -d -e DB_NAME=${{ secrets.DB_NAME }} \
                      -e MYSQL_USERNAME=${{ secrets.MYSQL_USERNAME }} \
                      -e MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
                      -e DB_IP=${{ secrets.DB_IP }} \
                      -e UPLOAD_ROOT=${{ secrets.UPLOAD_ROOT }} \
                      -e KAKAO_REDIRECT_URI=${{ secrets.KAKAO_REDIRECT_URI }} \
                      -e KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }} \
                      -e KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_ID }} \
                      -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
                      -e ALLOW_ORIGIN=${{ secrets.ALLOW_ORIGIN }} \
                      -p 8080:8080 
                      -p 443:443 
                      --name swyp6-back ${{ secrets.DOCKERHUB_USERNAME  }}/swyp6
            sudo docker image prune -f

