name: Docker Image Deploy

on:
  workflow_run:
    workflows: ["Docker Image Build"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to dev
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DEV }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            sudo docker ps
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/swyp6
            sudo docker stop swyp6-back || true
            sudo docker rm swyp6-back || true
            sudo docker run -d \
                      -p 8080:8080 \
                      -p 443:443 \
                      -p 80:80  \
                      -v /image:/image \
                      --name swyp6-back ${{ secrets.DOCKERHUB_USERNAME }}/swyp6
            sudo docker image prune -f
